from dags.ops.stores.city import CityETL
from dags.ops.stores.country import CountryETL
from dags.ops.stores.customer import CustomerETL
from dags.ops.stores.inventory import InventoryETL
from dags.ops.stores.product import ProductETL
from dags.ops.stores.productCategory import ProductCategoryETL
from dags.ops.stores.purchase import PurchaseETL
from dags.ops.stores.sales import SalesETL
from dags.ops.stores.salesStatus import SaleStatusETL
from dags.ops.stores.stores import StoresETL
from dags.ops.stores.storeType import StoreTypesETL
from dags.ops.stores.gender import GenderETL
from dags.ops.stores.maritalStatus import MaritalStatusETL
from dags.ops.stores.rating import RatingETL
from dags.ops.stores.customerType import CustomerTypeETL
